### ISSUE TITLE
Extend support for surrounding selected text with other characters.

### ISSUE THREAD

**Issue by pslobo** [careteditor/issues#312]
Currently, you can select some text and either press cmd+b or type ** to make the text bold. The selected text will remain selected and not be erased/overwritten.

One can't do that however with characters such as ` or  ~ so we can't easily select some text and convert it to strikethrough or inline code etc. (although it can be done when using the menu entry).

**Comment by borekb** [comment]
Both work for me and especially the backtick is something I use heavily.

**Comment by pslobo** [comment]
Weird. Then I suspect this must be something with my keyboard layout since with the Portuguese keyboard, the backtick is performed with the key combo shift+´. As for the tilde for strikethrough, that is just a normal keystroke so it's odd I can't get it to work.

![kapture 2017-04-20 at 16 40 24](https://cloud.githubusercontent.com/assets/1452095/25239509/19a5c778-25e8-11e7-8859-a9ff0e01ca3c.gif)
