### ISSUE TITLE
Complex Headers breaks tables

### ISSUE THREAD

**Issue by pslobo** [careteditor/issues#317]
When using a more complex table header, with multiple rows (valid markdown), tables break, both in the edit and in the preview/export.

Here's a quick example table that breaks:
```
| H1 || H2 ||
| Sub1 | Sub2 | Sub3 | Sub4 |
|:--:|:--:|:--:|:--:|
| Text1 | Text2  |  |  |
|  |  | Text3 | Text4 |
```
![screen shot 2017-04-22 at 11 33 51](https://cloud.githubusercontent.com/assets/1452095/25303676/d55636e8-274f-11e7-82c1-377939249c5d.png)
_Top: Broken, Middle: Expected result (iA Writer), Bottom: Working table but with single header row_

**Comment by erusev** [comment]
Is there a specification for complex tables? The current algorithm is designed around GitHub Flavored Markdown where complex tables don't seem to be supported.

**Comment by pslobo** [comment]
Ah, crap. Never realised that. Apparently this is MultiMarkdown specific only.

https://fletcher.github.io/MultiMarkdown-5/tables.html

No big issue then. I don't use this all that often that I'd say it's a deal breaker. Rather stick to GFM spec then ;)
