### ISSUE TITLE
Autosave too aggressive: Should be disabled for preferences.md and keyboard-shortcuts.md

### ISSUE THREAD

**Issue by pslobo** [careteditor/issues#333]
Autosave is a great feature, but it seems to be to aggressive and should be disabled for certain files such as `keyboard-shortcuts.md` and `preferences.md`.

Autosave seems to produce very strange behaviour when editing the keyboard-shortcuts.md file. I imagine we could easily run into certain similar issues when editing `preferences.md` one day.

Quick example of what seems to be corrupting my `keyboard-shortcuts.md`:
1. Open file,
2. Start to add shift as a keyboard modifier to a certain action. 
3. File gets saved mid-way (interruption or similar)
4. Now, each time I press shift to enter another key, the action gets triggered.

![kapture 2017-05-01 at 19 54 10](https://cloud.githubusercontent.com/assets/1452095/25590321/0446701c-2ea8-11e7-8d12-d0138ea1fea3.gif)

**Comment by borekb** [comment]
Possibly related: Strange contents of `keyboard-shortcuts.md` #278

**Comment by pslobo** [comment]
@borekb I thought it may be related too. But this isn't a caching issue and I've come across those too.
