### ISSUE TITLE
Feature Request: Add Support for iCloud Drive in File Navigator

### ISSUE THREAD

**Issue by pslobo** [careteditor/issues#334]
Now, this may be wishful thinking, but I do have some files stored in iCloud drive (from other apps that store their library there). I can use Alfred to search for and open the file in Caret, but then I can't really take full advantage of the file navigator when in another directory.

I'm pretty sure you'd have to hardcode some weird workaround for MacOS because iCloud Drive is an odd beast.

**Comment by BsNoSi** [comment]
Maybe this schould be extended to "named places" or "Favorites", a list of i.e. five adresses, stored in configuration. This can be iCloud, NextCloud, OneDrive, or simply “MyDocuments/MD-Files“.

**Comment by pslobo** [comment]
I like this idea. I really don't need to see every folder in in my user 
home like Pictures, Music etc. Having a filter or list of 
folders/locations that will show up by default in the file navigator 
would be rather cool.
